apiVersion: v1
data:
  SERVER_ADDRESS: golang-grpc-server.devsecops-meetup.svc.cluster.local
  SERVER_PORT: "50051"
kind: ConfigMap
metadata:
  name: golang-grpc-config
  namespace: devsecops-meetup
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: employee-database
  namespace: devsecops-meetup
data:
  EMPLOYEES: |
    [
      {
        "id": 1,
        "email": "abcd@abcd.com",
        "firstName": "First1",
        "lastName": "Last1"
      },
      {
        "id": 2,
        "email": "xyz@xyz.com",
        "firstName": "First2",
        "lastName": "Last2"
      },
      {
        "id": 3,
        "email": "pqr@pqr.com",
        "firstName": "First3",
        "lastName": "Last3"
      },
      {
        "id": 4,
        "email": "lmn@lmn.com",
        "firstName": "First4",
        "lastName": "Last4"
      }
    ]
